sudo: false
language: python
cache: pip
python:
  - "3.6"
env:
  - BASEDIR="https://raw.githubusercontent.com/open-contracting/standard-maintenance-scripts/master"
install:
  - curl -s -S $BASEDIR/tests/install.sh | bash -
  - pip install -e .
script:
  - curl -s -S $BASEDIR/tests/script.sh | bash -
jobs:
  include:
    - stage: test
      script: python test_registry.py
    - stage: test
      install: pip install json_merge_patch requests -e git+https://github.com/OpenDataServices/flatten-tool.git@master#egg=flattentool
      script: python extra/test_flattentool.py
notifications:
  email:
    recipients:
      - code@opendataservices.coop
      - jmckinney+github@open-contracting.org
    on_success: never # default: change
    on_failure: always # default: always
